apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mlflow
  namespace: mlflow
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mlflow.kube.lab`)
      kind: Rule
      services:
        - name: mlflow
          port: 5000
  tls: {} # This triggers the use of the Traefik default certificate